//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obuv1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_
    {
        public int ID { get; set; }
        public string Name_ { get; set; }
        public string Surname { get; set; }
        public string City { get; set; }
        public string Address_ { get; set; }
        public string Phone { get; set; }
        public int Id_Shoes { get; set; }
    
        public virtual Shoes Shoes { get; set; }
    }
}
